In [1]:
!pip install -U transformers accelerate peft

Requirement already satisfied: transformers in /usr/local/lib/python3.12/dist-packages (5.0.0)
Collecting transformers
  Downloading transformers-5.7.0-py3-none-any.whl.metadata (33 kB)
Requirement already satisfied: accelerate in /usr/local/lib/python3.12/dist-packages (1.12.0)
Collecting accelerate
  Downloading accelerate-1.13.0-py3-none-any.whl.metadata (19 kB)
Requirement already satisfied: peft in /usr/local/lib/python3.12/dist-packages (0.18.1)
Collecting peft
  Downloading peft-0.19.1-py3-none-any.whl.metadata (15 kB)
Collecting huggingface-hub<2.0,>=1.5.0 (from transformers)
  Downloading huggingface_hub-1.12.0-py3-none-any.whl.metadata (14 kB)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.12/dist-packages (from transformers) (2.0.2)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from transformers) (26.0)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.12/dist-packages (from transformers) (6.0.3)
Requirement already satisfied: regex>=2025.10.22 in /usr/local/lib/python3.12/dist-packages (from transformers) (2025.11.3)
Requirement already satisfied: tokenizers<=0.23.0,>=0.22.0 in /usr/local/lib/python3.12/dist-packages (from transformers) (0.22.2)
Requirement already satisfied: typer in /usr/local/lib/python3.12/dist-packages (from transformers) (0.24.1)
Requirement already satisfied: safetensors>=0.4.3 in /usr/local/lib/python3.12/dist-packages (from transformers) (0.7.0)
Requirement already satisfied: tqdm>=4.27 in /usr/local/lib/python3.12/dist-packages (from transformers) (4.67.3)
Requirement already satisfied: psutil in /usr/local/lib/python3.12/dist-packages (from accelerate) (5.9.5)
Requirement already satisfied: torch>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from accelerate) (2.10.0+cu128)
Requirement already satisfied: filelock>=3.10.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=1.5.0->transformers) (3.24.3)
Requirement already satisfied: fsspec>=2023.5.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=1.5.0->transformers) (2026.2.0)
Collecting hf-xet<2.0.0,>=1.4.3 (from huggingface-hub<2.0,>=1.5.0->transformers)
  Downloading hf_xet-1.4.3-cp37-abi3-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (4.9 kB)
Requirement already satisfied: httpx<1,>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=1.5.0->transformers) (0.28.1)
Requirement already satisfied: typing-extensions>=4.1.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=1.5.0->transformers) (4.15.0)
Requirement already satisfied: setuptools in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (75.2.0)
Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (3.6.1)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (3.1.6)
Requirement already satisfied: cuda-bindings==12.9.4 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (12.9.4)
Requirement already satisfied: nvidia-cuda-nvrtc-cu12==12.8.93 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (12.8.93)
Requirement already satisfied: nvidia-cuda-runtime-cu12==12.8.90 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (12.8.90)
Requirement already satisfied: nvidia-cuda-cupti-cu12==12.8.90 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (12.8.90)
Requirement already satisfied: nvidia-cudnn-cu12==9.10.2.21 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (9.10.2.21)
Requirement already satisfied: nvidia-cublas-cu12==12.8.4.1 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (12.8.4.1)
Requirement already satisfied: nvidia-cufft-cu12==11.3.3.83 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (11.3.3.83)
Requirement already satisfied: nvidia-curand-cu12==10.3.9.90 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (10.3.9.90)
Requirement already satisfied: nvidia-cusolver-cu12==11.7.3.90 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (11.7.3.90)
Requirement already satisfied: nvidia-cusparse-cu12==12.5.8.93 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (12.5.8.93)
Requirement already satisfied: nvidia-cusparselt-cu12==0.7.1 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (0.7.1)
Requirement already satisfied: nvidia-nccl-cu12==2.27.5 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (2.27.5)
Requirement already satisfied: nvidia-nvshmem-cu12==3.4.5 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (3.4.5)
Requirement already satisfied: nvidia-nvtx-cu12==12.8.90 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (12.8.90)
Requirement already satisfied: nvidia-nvjitlink-cu12==12.8.93 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (12.8.93)
Requirement already satisfied: nvidia-cufile-cu12==1.13.1.3 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (1.13.1.3)
Requirement already satisfied: triton==3.6.0 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (3.6.0)
Requirement already satisfied: cuda-pathfinder~=1.1 in /usr/local/lib/python3.12/dist-packages (from cuda-bindings==12.9.4->torch>=2.0.0->accelerate) (1.3.5)
Requirement already satisfied: click>=8.2.1 in /usr/local/lib/python3.12/dist-packages (from typer->transformers) (8.3.1)
Requirement already satisfied: shellingham>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from typer->transformers) (1.5.4)
Requirement already satisfied: rich>=12.3.0 in /usr/local/lib/python3.12/dist-packages (from typer->transformers) (13.9.4)
Requirement already satisfied: annotated-doc>=0.0.2 in /usr/local/lib/python3.12/dist-packages (from typer->transformers) (0.0.4)
Requirement already satisfied: anyio in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers) (4.12.1)
Requirement already satisfied: certifi in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers) (2026.1.4)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers) (1.0.9)
Requirement already satisfied: idna in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers) (3.11)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers) (0.16.0)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from rich>=12.3.0->typer->transformers) (4.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from rich>=12.3.0->typer->transformers) (2.19.2)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from sympy>=1.13.3->torch>=2.0.0->accelerate) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->torch>=2.0.0->accelerate) (3.0.3)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=2.2.0->rich>=12.3.0->typer->transformers) (0.1.2)
Downloading transformers-5.7.0-py3-none-any.whl (10.5 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 10.5/10.5 MB 113.3 MB/s eta 0:00:00
Downloading accelerate-1.13.0-py3-none-any.whl (383 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 383.7/383.7 kB 22.5 MB/s eta 0:00:00
Downloading peft-0.19.1-py3-none-any.whl (680 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 680.7/680.7 kB 41.0 MB/s eta 0:00:00
Downloading huggingface_hub-1.12.0-py3-none-any.whl (646 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 646.8/646.8 kB 31.6 MB/s eta 0:00:00
Downloading hf_xet-1.4.3-cp37-abi3-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (4.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.2/4.2 MB 102.5 MB/s eta 0:00:00
Installing collected packages: hf-xet, huggingface-hub, accelerate, transformers, peft
  Attempting uninstall: hf-xet
    Found existing installation: hf-xet 1.3.0
    Uninstalling hf-xet-1.3.0:
      Successfully uninstalled hf-xet-1.3.0
  Attempting uninstall: huggingface-hub
    Found existing installation: huggingface_hub 1.4.1
    Uninstalling huggingface_hub-1.4.1:
      Successfully uninstalled huggingface_hub-1.4.1
  Attempting uninstall: accelerate
    Found existing installation: accelerate 1.12.0
    Uninstalling accelerate-1.12.0:
      Successfully uninstalled accelerate-1.12.0
  Attempting uninstall: transformers
    Found existing installation: transformers 5.0.0
    Uninstalling transformers-5.0.0:
      Successfully uninstalled transformers-5.0.0
  Attempting uninstall: peft
    Found existing installation: peft 0.18.1
    Uninstalling peft-0.18.1:
      Successfully uninstalled peft-0.18.1
Successfully installed accelerate-1.13.0 hf-xet-1.4.3 huggingface-hub-1.12.0 peft-0.19.1 transformers-5.7.0

In [2]:
!pip install -q evaluate

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 84.1/84.1 kB 4.2 MB/s eta 0:00:00

In [3]:
! pip install --upgrade datasets pyarrow

Requirement already satisfied: datasets in /usr/local/lib/python3.12/dist-packages (4.8.3)
Collecting datasets
  Downloading datasets-4.8.5-py3-none-any.whl.metadata (19 kB)
Requirement already satisfied: pyarrow in /usr/local/lib/python3.12/dist-packages (23.0.1)
Collecting pyarrow
  Downloading pyarrow-24.0.0-cp312-cp312-manylinux_2_28_x86_64.whl.metadata (3.0 kB)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from datasets) (3.24.3)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.12/dist-packages (from datasets) (2.0.2)
Requirement already satisfied: dill<0.4.2,>=0.3.0 in /usr/local/lib/python3.12/dist-packages (from datasets) (0.4.1)
Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (from datasets) (2.3.3)
Requirement already satisfied: requests>=2.32.2 in /usr/local/lib/python3.12/dist-packages (from datasets) (2.32.4)
Requirement already satisfied: httpx<1.0.0 in /usr/local/lib/python3.12/dist-packages (from datasets) (0.28.1)
Requirement already satisfied: tqdm>=4.66.3 in /usr/local/lib/python3.12/dist-packages (from datasets) (4.67.3)
Requirement already satisfied: xxhash in /usr/local/lib/python3.12/dist-packages (from datasets) (3.6.0)
Requirement already satisfied: multiprocess<0.70.20 in /usr/local/lib/python3.12/dist-packages (from datasets) (0.70.16)
Requirement already satisfied: fsspec<=2026.2.0,>=2023.1.0 in /usr/local/lib/python3.12/dist-packages (from fsspec[http]<=2026.2.0,>=2023.1.0->datasets) (2026.2.0)
Requirement already satisfied: huggingface-hub<2.0,>=0.25.0 in /usr/local/lib/python3.12/dist-packages (from datasets) (1.12.0)
Requirement already satisfied: packaging in /usr/local/lib/python3.12/dist-packages (from datasets) (26.0)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.12/dist-packages (from datasets) (6.0.3)
Requirement already satisfied: aiohttp!=4.0.0a0,!=4.0.0a1 in /usr/local/lib/python3.12/dist-packages (from fsspec[http]<=2026.2.0,>=2023.1.0->datasets) (3.13.3)
Requirement already satisfied: anyio in /usr/local/lib/python3.12/dist-packages (from httpx<1.0.0->datasets) (4.12.1)
Requirement already satisfied: certifi in /usr/local/lib/python3.12/dist-packages (from httpx<1.0.0->datasets) (2026.1.4)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx<1.0.0->datasets) (1.0.9)
Requirement already satisfied: idna in /usr/local/lib/python3.12/dist-packages (from httpx<1.0.0->datasets) (3.11)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx<1.0.0->datasets) (0.16.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.4.3 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=0.25.0->datasets) (1.4.3)
Requirement already satisfied: typer in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=0.25.0->datasets) (0.24.1)
Requirement already satisfied: typing-extensions>=4.1.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=0.25.0->datasets) (4.15.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests>=2.32.2->datasets) (3.4.4)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests>=2.32.2->datasets) (2.5.0)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas->datasets) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas->datasets) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas->datasets) (2025.3)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.2.0,>=2023.1.0->datasets) (2.6.1)
Requirement already satisfied: aiosignal>=1.4.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.2.0,>=2023.1.0->datasets) (1.4.0)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.2.0,>=2023.1.0->datasets) (25.4.0)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.2.0,>=2023.1.0->datasets) (1.8.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.2.0,>=2023.1.0->datasets) (6.7.1)
Requirement already satisfied: propcache>=0.2.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.2.0,>=2023.1.0->datasets) (0.4.1)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.2.0,>=2023.1.0->datasets) (1.22.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas->datasets) (1.17.0)
Requirement already satisfied: click>=8.2.1 in /usr/local/lib/python3.12/dist-packages (from typer->huggingface-hub<2.0,>=0.25.0->datasets) (8.3.1)
Requirement already satisfied: shellingham>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from typer->huggingface-hub<2.0,>=0.25.0->datasets) (1.5.4)
Requirement already satisfied: rich>=12.3.0 in /usr/local/lib/python3.12/dist-packages (from typer->huggingface-hub<2.0,>=0.25.0->datasets) (13.9.4)
Requirement already satisfied: annotated-doc>=0.0.2 in /usr/local/lib/python3.12/dist-packages (from typer->huggingface-hub<2.0,>=0.25.0->datasets) (0.0.4)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from rich>=12.3.0->typer->huggingface-hub<2.0,>=0.25.0->datasets) (4.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from rich>=12.3.0->typer->huggingface-hub<2.0,>=0.25.0->datasets) (2.19.2)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=2.2.0->rich>=12.3.0->typer->huggingface-hub<2.0,>=0.25.0->datasets) (0.1.2)
Downloading datasets-4.8.5-py3-none-any.whl (528 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 529.0/529.0 kB 20.5 MB/s eta 0:00:00
Downloading pyarrow-24.0.0-cp312-cp312-manylinux_2_28_x86_64.whl (48.9 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 48.9/48.9 MB 41.3 MB/s eta 0:00:00
Installing collected packages: pyarrow, datasets
  Attempting uninstall: pyarrow
    Found existing installation: pyarrow 23.0.1
    Uninstalling pyarrow-23.0.1:
      Successfully uninstalled pyarrow-23.0.1
  Attempting uninstall: datasets
    Found existing installation: datasets 4.8.3
    Uninstalling datasets-4.8.3:
      Successfully uninstalled datasets-4.8.3
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
bigframes 2.35.0 requires google-cloud-bigquery-storage<3.0.0,>=2.30.0, which is not installed.
google-adk 1.25.1 requires google-cloud-bigquery-storage>=2.0.0, which is not installed.
Successfully installed datasets-4.8.5 pyarrow-24.0.0

In [4]:
! pip install jiwer

Collecting jiwer
  Downloading jiwer-4.0.0-py3-none-any.whl.metadata (3.3 kB)
Requirement already satisfied: click>=8.1.8 in /usr/local/lib/python3.12/dist-packages (from jiwer) (8.3.1)
Collecting rapidfuzz>=3.9.7 (from jiwer)
  Downloading rapidfuzz-3.14.5-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl.metadata (12 kB)
Downloading jiwer-4.0.0-py3-none-any.whl (23 kB)
Downloading rapidfuzz-3.14.5-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl (3.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.1/3.1 MB 76.3 MB/s eta 0:00:00
Installing collected packages: rapidfuzz, jiwer
Successfully installed jiwer-4.0.0 rapidfuzz-3.14.5

In [5]:
import os, re, gc, time, shutil, json
import numpy as np
import pandas as pd
import torch
import librosa
import evaluate

from dataclasses import dataclass
from typing import Any, Dict, List, Optional
from pathlib import Path

from datasets import (
    Dataset, DatasetDict,
    Array2D, Sequence, Value, Features,
    Audio as HFAudio,
)
from transformers import (
    WhisperProcessor,
    WhisperForConditionalGeneration,
    Seq2SeqTrainer,
    Seq2SeqTrainingArguments,
    EarlyStoppingCallback,
)

# ── GPU diagnostics ──────────────────────────────────────────────────────────
print(f'PyTorch  : {torch.__version__}')
print(f'CUDA     : {torch.version.cuda}')
print(f'GPU      : {torch.cuda.get_device_name(0) if torch.cuda.is_available() else "CPU"}')
if torch.cuda.is_available():
    cap = torch.cuda.get_device_capability(0)
    vram = torch.cuda.get_device_properties(0).total_memory / 1e9
    print(f'VRAM     : {vram:.1f} GB')
    print(f'sm_cap   : sm_{cap[0]}{cap[1]}')
    # Quick tensor test — fails immediately if CUDA ABI mismatch
    try:
        _ = torch.randn(4, 4).cuda() @ torch.randn(4, 4).cuda()
        print('GPU test : ✅ OK')
    except Exception as e:
        print(f'GPU test : ❌ FAILED — {e}')
        print('Switch accelerator to T4 in Kaggle settings!')

PyTorch  : 2.10.0+cu128
CUDA     : 12.8
GPU      : Tesla T4
VRAM     : 15.6 GB
sm_cap   : sm_75
GPU test : ✅ OK

In [6]:
CFG = {
    # ── Dataset ──────────────────────────────────────────────────────
    # Root folder of your uploaded Common Voice 25.0 Arabic dataset
    'data_root': '/kaggle/input/datasets/omar10lfc/common-voice-scripted-speech-25-0-arabic',

    # How many TRAINING samples to use.
    # Common Voice Arabic train.tsv has 28,865 rows.
    # Recommended sizes:
    #   Quick test  : 1_000  (~15 min feature extraction, ~20 min training)
    #   Good result : 5_000  (~45 min feature extraction, ~1 hr training)
    #   Full run    : 28_865 (~3 hrs feature extraction,  ~4 hrs training)
    'n_train': 25000,

    # How many TEST samples to evaluate on.
    # Keeping this small makes eval fast (WER computation is slow).
    'n_test': 300,

    # Random seed — controls shuffle order (reproducible)
    'seed': 42,

    # ── Model ─────────────────────────────────────────────────────────
    # 'openai/whisper-tiny'   — 39M  params, fastest,  lowest quality
    # 'openai/whisper-small'  — 244M params, balanced  ← recommended
    # 'openai/whisper-medium' — 769M params, best quality, needs 16GB+
    'model_name': 'openai/whisper-small',

    # ── Training ──────────────────────────────────────────────────────
    # Tuned for ~20s WER in less wall time:
    #   - LR 1e-5 is the standard for whisper-small fine-tuning (HF blog).
    #     5e-6 was too cold; convergence was slow.
    #   - 1200 steps × eff-batch 32 ≈ 3.8 passes over 10k clips —
    #     enough at the higher LR. More was marginal gains for big compute.
    #   - eval/save every 400 → 3 checkpoints, so early-stopping + best-model
    #     selection actually find the right point instead of overshooting.
    'max_steps': 2000,
    'eval_steps': 500,
    'save_steps': 500,
    'logging_steps': 25,
    'batch_size': 8,           # Per-device batch size
    'grad_accumulation': 4,     # Effective batch = batch_size * grad_accumulation
    'learning_rate': 1e-5,
    'warmup_steps': 500,
    'weight_decay': 0.01,
    'num_workers': 2,
    'early_stopping_patience': 3,  # Stop if WER doesn't improve for N evals

    # ── Paths ─────────────────────────────────────────────────────────
    'output_dir':   '/kaggle/working/whisper-arabic',
    'cache_dir':    '/kaggle/tmp/whisper_cache',
}

# Create output dirs
os.makedirs(CFG['output_dir'], exist_ok=True)
os.makedirs(CFG['cache_dir'],  exist_ok=True)

print('Configuration:')
for k, v in CFG.items():
    print(f'  {k:25s}: {v}')

Configuration:
  data_root                : /kaggle/input/datasets/omar10lfc/common-voice-scripted-speech-25-0-arabic
  n_train                  : 25000
  n_test                   : 300
  seed                     : 42
  model_name               : openai/whisper-small
  max_steps                : 2000
  eval_steps               : 500
  save_steps               : 500
  logging_steps            : 25
  batch_size               : 8
  grad_accumulation        : 4
  learning_rate            : 1e-05
  warmup_steps             : 500
  weight_decay             : 0.01
  num_workers              : 2
  early_stopping_patience  : 3
  output_dir               : /kaggle/working/whisper-arabic
  cache_dir                : /kaggle/tmp/whisper_cache

In [7]:
# WHY: Common Voice 25.0 is split across 1900+ numbered subdirectories.
# We do ONE os.walk() pass to build a lookup dict: filename_stem → full_path.
# This is much faster than searching the tree per sample.

print(f'Scanning {CFG["data_root"]} ...')
t0 = time.time()

tsv_index   = {}   # 'train' / 'dev' / 'test' → full .tsv path
audio_index = {}   # 'common_voice_ar_XXXXX'  → full .mp3 path

for root, _, files in os.walk(CFG['data_root']):
    for fname in files:
        full = os.path.join(root, fname)
        if fname.endswith('.tsv'):
            stem = fname[:-4]   # remove .tsv
            if stem not in tsv_index:
                tsv_index[stem] = full
        elif fname.endswith(('.mp3', '.wav', '.ogg', '.m4a')):
            stem = os.path.splitext(fname)[0]
            audio_index[stem] = full

print(f'Scan done in {time.time()-t0:.1f}s')
print(f'TSV files : {list(tsv_index.keys())}')
print(f'Audio clips: {len(audio_index):,}')

Scanning /kaggle/input/datasets/omar10lfc/common-voice-scripted-speech-25-0-arabic ...
Scan done in 311.9s
TSV files : ['test', 'dev', 'train', 'clip_durations', 'unvalidated_sentences', 'validated_sentences', 'invalidated', 'other', 'validated', 'reported']
Audio clips: 136,140

In [8]:
# WHY normalize_arabic: Whisper outputs normalized text but ground truth has
# diacritics, alef variants, etc. Computing WER on raw text inflates the score.
# We normalize BOTH hypothesis and reference before any WER computation.

def normalize_arabic(text: str) -> str:
    if not isinstance(text, str):
        return ''
    text = re.sub(r'[إأآٱ]', 'ا', text)              # alef variants → ا
    text = re.sub(r'ى', 'ي', text)                    # ya variants → ي
    text = re.sub(r'ة', 'ه', text)                    # ta marbuta → ه
    text = re.sub(r'[\u064B-\u065F\u0670]', '', text) # strip diacritics
    text = re.sub(r'ـ', '', text)                      # strip tatweel
    text = re.sub(r'[^\w\s\u0600-\u06FF]', '', text)  # keep Arabic + alphanum
    text = re.sub(r'\s+', ' ', text)
    return text.strip()


def load_tsv(key: str, n_samples: Optional[int] = None, seed: int = 42) -> pd.DataFrame:
    """
    Load a TSV split, resolve audio paths, normalize text.
    Shuffles BEFORE subsampling so the subset is representative.
    """
    if key not in tsv_index:
        raise FileNotFoundError(f'{key}.tsv not found. Available: {list(tsv_index)}')

    df = pd.read_csv(tsv_index[key], sep='\t', low_memory=False)
    print(f'[{key}] Loaded {len(df):,} rows')

    # Resolve columns — CV 25.0 uses 'path' and 'sentence'
    path_col = 'path' if 'path' in df.columns else df.columns[1]
    text_col = 'sentence' if 'sentence' in df.columns else 'text'

    # Resolve audio paths
    def resolve(raw):
        stem = os.path.splitext(os.path.basename(str(raw)))[0]
        return audio_index.get(stem)

    df['audio_path'] = df[path_col].apply(resolve)
    df['sentence']   = df[text_col].apply(normalize_arabic)

    # Drop rows with missing audio or empty text
    before = len(df)
    df = df.dropna(subset=['audio_path'])
    df = df[df['sentence'].str.len() > 2]
    df = df[['audio_path', 'sentence']].reset_index(drop=True)
    print(f'  → {len(df):,} valid rows (dropped {before - len(df):,})')

    # Shuffle BEFORE subsampling — ensures representative subset
    df = df.sample(frac=1, random_state=seed).reset_index(drop=True)

    # Subsample
    if n_samples and n_samples < len(df):
        df = df.iloc[:n_samples].reset_index(drop=True)
        print(f'  → Subsampled to {len(df):,} rows')

    return df


# Load train (combine train + dev for more data), test separately
df_train_raw = load_tsv('train', seed=CFG['seed'])
df_dev_raw   = load_tsv('dev',   seed=CFG['seed'])
df_test_raw  = load_tsv('test',  n_samples=CFG['n_test'], seed=CFG['seed'])

# Combine train + dev, shuffle again, then subsample
df_all = pd.concat([df_train_raw, df_dev_raw], ignore_index=True)
df_all = df_all.sample(frac=1, random_state=CFG['seed']).reset_index(drop=True)
df_train = df_all.iloc[:CFG['n_train']].reset_index(drop=True)

print(f'\n✅ Final split sizes:')
print(f'  Train : {len(df_train):,}')
print(f'  Test  : {len(df_test_raw):,}')
print(f'\nSample:')
print(df_train.iloc[0])

[train] Loaded 28,865 rows
  → 28,862 valid rows (dropped 3)
[dev] Loaded 10,229 rows
  → 10,227 valid rows (dropped 2)
[test] Loaded 10,508 rows
  → 10,506 valid rows (dropped 2)
  → Subsampled to 300 rows

✅ Final split sizes:
  Train : 25,000
  Test  : 300

Sample:
audio_path    /kaggle/input/datasets/omar10lfc/common-voice-...
sentence                                           قتلت بتي امه
Name: 0, dtype: object

In [9]:
# WHY load model before feature extraction:
# The processor defines the feature extractor config (n_mels, hop_length etc.)
# We need it to extract features correctly.

print(f'Loading {CFG["model_name"]}...')

processor = WhisperProcessor.from_pretrained(
    CFG['model_name'],
    language='Arabic',
    task='transcribe',
)

model = WhisperForConditionalGeneration.from_pretrained(CFG['model_name'])

# Force Arabic — without this Whisper may auto-detect language
# and switch to English mid-batch, producing garbage outputs.
model.generation_config.language = 'arabic'
model.generation_config.task = 'transcribe'
model.generation_config.forced_decoder_ids = None

print(f'Parameters: {model.num_parameters():,}')
print(f'Encoder layers: {model.config.encoder_layers}')
print(f'Decoder layers: {model.config.decoder_layers}')

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

Loading openai/whisper-small...

preprocessor_config.json: 0.00B [00:00, ?B/s]

config.json: 0.00B [00:00, ?B/s]

tokenizer_config.json: 0.00B [00:00, ?B/s]

vocab.json: 0.00B [00:00, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

merges.txt: 0.00B [00:00, ?B/s]

normalizer.json: 0.00B [00:00, ?B/s]

added_tokens.json: 0.00B [00:00, ?B/s]

special_tokens_map.json: 0.00B [00:00, ?B/s]

model.safetensors:   0%|          | 0.00/967M [00:00<?, ?B/s]

Loading weights:   0%|          | 0/479 [00:00<?, ?it/s]

generation_config.json: 0.00B [00:00, ?B/s]

Parameters: 241,734,912
Encoder layers: 12
Decoder layers: 12

In [10]:
# WHY chunk + save to /kaggle/tmp:
# Processing all 5000 samples at once loads ~5GB of float32 audio into RAM,
# which crashes the kernel. Chunks of 300 keep peak RAM under 2GB.
# /kaggle/tmp has a separate quota from /kaggle/working.
#
# WHY explicit Array2D schema:
# Without it, HuggingFace stores spectrograms as nested Python lists,
# making DataLoader access ~50x slower than Arrow-backed arrays.

ARROW_FEATURES = Features({
    'input_features': Array2D(shape=(80, 3000), dtype='float32'),
    'labels':         Sequence(Value('int64')),
})


def extract_features(
    df: pd.DataFrame,
    split_name: str,
    chunk_size: int = 300,
) -> Dataset:
    """
    Extract log-mel features + token labels from a dataframe.
    Processes in chunks to keep RAM flat.
    Skips chunks already on disk (safe to re-run after crash).
    """
    cache = os.path.join(CFG['cache_dir'], split_name)
    os.makedirs(cache, exist_ok=True)

    total    = len(df)
    n_chunks = (total + chunk_size - 1) // chunk_size
    done_paths = []
    skipped = 0

    for i in range(n_chunks):
        chunk_path = os.path.join(cache, f'chunk_{i:04d}')

        # Resume: skip already-processed chunks
        if os.path.exists(os.path.join(chunk_path, 'dataset_info.json')):
            done_paths.append(chunk_path)
            skipped += 1
            continue

        start = i * chunk_size
        end   = min(start + chunk_size, total)
        rows  = df.iloc[start:end]

        feats_list  = []
        labels_list = []

        for _, row in rows.iterrows():
            try:
                # Load + resample to 16kHz — Whisper requirement
                audio, _ = librosa.load(row['audio_path'], sr=16000, mono=True)

                # Skip clips outside 0.5–29s range
                # (too short = mostly noise; >29s gets truncated by Whisper)
                duration = len(audio) / 16000
                if not (0.5 <= duration <= 29.0):
                    continue

                # Log-mel spectrogram: (80, 3000) fixed size
                feat = processor.feature_extractor(
                    audio,
                    sampling_rate=16000,
                ).input_features[0].astype(np.float32)

                # Tokenize transcript
                token_ids = processor.tokenizer(
                    row['sentence']
                ).input_ids

                feats_list.append(feat)
                labels_list.append(token_ids)

            except Exception:
                continue   # skip corrupted files silently

        if not feats_list:
            continue

        # Build Arrow dataset with explicit schema — critical for speed
        chunk_ds = Dataset.from_dict(
            {
                'input_features': np.array(feats_list, dtype=np.float32),
                'labels':         labels_list,
            },
            features=ARROW_FEATURES,
        )
        chunk_ds.save_to_disk(chunk_path)
        done_paths.append(chunk_path)

        # Explicitly free memory
        del feats_list, labels_list, chunk_ds
        gc.collect()

        pct = end / total * 100
        print(f'  [{split_name}] {i+1}/{n_chunks} — {end:,}/{total:,} ({pct:.0f}%)',
              flush=True)

    if skipped:
        print(f'  [{split_name}] Skipped {skipped} already-done chunks (resume)')

    # Load and concatenate all chunks
    print(f'  [{split_name}] Concatenating {len(done_paths)} chunks...')
    from datasets import concatenate_datasets
    all_chunks = [Dataset.load_from_disk(p) for p in done_paths]
    result = concatenate_datasets(all_chunks)
    
    # REMOVED: result = result.with_format('numpy') 
    # Bypassing this prevents the internal numpy=2.0 crash in Hugging Face datasets.

    # Clean up chunks — data is now in memory
    for p in done_paths:
        shutil.rmtree(p, ignore_errors=True)

    print(f'  [{split_name}] ✅ {len(result):,} samples ready')
    return result


print('=== Extracting TRAIN features ===')
train_dataset = extract_features(df_train,   'train')

print('\n=== Extracting TEST features ===')
test_dataset  = extract_features(df_test_raw, 'test')

dataset = DatasetDict({'train': train_dataset, 'test': test_dataset})

print(f'\n✅ Feature extraction complete')
print(f'  Train : {len(dataset["train"]):,}')
print(f'  Test  : {len(dataset["test"]):,}')
# Safely convert to numpy array using np.asarray() as recommended by NumPy 2.0+
print(f'  Shape : {np.asarray(dataset["train"][0]["input_features"]).shape}')

=== Extracting TRAIN features ===

Saving the dataset (0/1 shards):   0%|          | 0/300 [00:00<?, ? examples/s]

  [train] 1/84 — 300/25,000 (1%)

Saving the dataset (0/1 shards):   0%|          | 0/300 [00:00<?, ? examples/s]

  [train] 2/84 — 600/25,000 (2%)

Saving the dataset (0/1 shards):   0%|          | 0/300 [00:00<?, ? examples/s]

  [train] 3/84 — 900/25,000 (4%)

Saving the dataset (0/1 shards):   0%|          | 0/300 [00:00<?, ? examples/s]

  [train] 4/84 — 1,200/25,000 (5%)

Saving the dataset (0/1 shards):   0%|          | 0/300 [00:00<?, ? examples/s]

  [train] 5/84 — 1,500/25,000 (6%)

Saving the dataset (0/1 shards):   0%|          | 0/300 [00:00<?, ? examples/s]

  [train] 6/84 — 1,800/25,000 (7%)

Saving the dataset (0/1 shards):   0%|          | 0/300 [00:00<?, ? examples/s]

  [train] 7/84 — 2,100/25,000 (8%)

Saving the dataset (0/1 shards):   0%|          | 0/300 [00:00<?, ? examples/s]

  [train] 8/84 — 2,400/25,000 (10%)

Saving the dataset (0/1 shards):   0%|          | 0/300 [00:00<?, ? examples/s]

  [train] 9/84 — 2,700/25,000 (11%)

Saving the dataset (0/1 shards):   0%|          | 0/300 [00:00<?, ? examples/s]

  [train] 10/84 — 3,000/25,000 (12%)

Saving the dataset (0/1 shards):   0%|          | 0/300 [00:00<?, ? examples/s]

  [train] 11/84 — 3,300/25,000 (13%)

Saving the dataset (0/1 shards):   0%|          | 0/300 [00:00<?, ? examples/s]

  [train] 12/84 — 3,600/25,000 (14%)

Saving the dataset (0/1 shards):   0%|          | 0/300 [00:00<?, ? examples/s]

  [train] 13/84 — 3,900/25,000 (16%)

Saving the dataset (0/1 shards):   0%|          | 0/300 [00:00<?, ? examples/s]

  [train] 14/84 — 4,200/25,000 (17%)

Saving the dataset (0/1 shards):   0%|          | 0/300 [00:00<?, ? examples/s]

  [train] 15/84 — 4,500/25,000 (18%)

Saving the dataset (0/1 shards):   0%|          | 0/300 [00:00<?, ? examples/s]

  [train] 16/84 — 4,800/25,000 (19%)

Saving the dataset (0/1 shards):   0%|          | 0/300 [00:00<?, ? examples/s]

  [train] 17/84 — 5,100/25,000 (20%)

Saving the dataset (0/1 shards):   0%|          | 0/300 [00:00<?, ? examples/s]

  [train] 18/84 — 5,400/25,000 (22%)

Saving the dataset (0/1 shards):   0%|          | 0/300 [00:00<?, ? examples/s]

  [train] 19/84 — 5,700/25,000 (23%)

Saving the dataset (0/1 shards):   0%|          | 0/300 [00:00<?, ? examples/s]

  [train] 20/84 — 6,000/25,000 (24%)

Saving the dataset (0/1 shards):   0%|          | 0/300 [00:00<?, ? examples/s]

  [train] 21/84 — 6,300/25,000 (25%)

Saving the dataset (0/1 shards):   0%|          | 0/300 [00:00<?, ? examples/s]

  [train] 22/84 — 6,600/25,000 (26%)

Saving the dataset (0/1 shards):   0%|          | 0/300 [00:00<?, ? examples/s]

  [train] 23/84 — 6,900/25,000 (28%)

Saving the dataset (0/1 shards):   0%|          | 0/300 [00:00<?, ? examples/s]

  [train] 24/84 — 7,200/25,000 (29%)

Saving the dataset (0/1 shards):   0%|          | 0/300 [00:00<?, ? examples/s]

  [train] 25/84 — 7,500/25,000 (30%)

Saving the dataset (0/1 shards):   0%|          | 0/300 [00:00<?, ? examples/s]

  [train] 26/84 — 7,800/25,000 (31%)

Saving the dataset (0/1 shards):   0%|          | 0/300 [00:00<?, ? examples/s]

  [train] 27/84 — 8,100/25,000 (32%)

Saving the dataset (0/1 shards):   0%|          | 0/300 [00:00<?, ? examples/s]

  [train] 28/84 — 8,400/25,000 (34%)

Saving the dataset (0/1 shards):   0%|          | 0/300 [00:00<?, ? examples/s]

  [train] 29/84 — 8,700/25,000 (35%)

Saving the dataset (0/1 shards):   0%|          | 0/300 [00:00<?, ? examples/s]

  [train] 30/84 — 9,000/25,000 (36%)

Saving the dataset (0/1 shards):   0%|          | 0/300 [00:00<?, ? examples/s]

  [train] 31/84 — 9,300/25,000 (37%)

Saving the dataset (0/1 shards):   0%|          | 0/300 [00:00<?, ? examples/s]

  [train] 32/84 — 9,600/25,000 (38%)

Saving the dataset (0/1 shards):   0%|          | 0/300 [00:00<?, ? examples/s]

  [train] 33/84 — 9,900/25,000 (40%)

Saving the dataset (0/1 shards):   0%|          | 0/300 [00:00<?, ? examples/s]

  [train] 34/84 — 10,200/25,000 (41%)

Saving the dataset (0/1 shards):   0%|          | 0/300 [00:00<?, ? examples/s]

  [train] 35/84 — 10,500/25,000 (42%)

Saving the dataset (0/1 shards):   0%|          | 0/300 [00:00<?, ? examples/s]

  [train] 36/84 — 10,800/25,000 (43%)

Saving the dataset (0/1 shards):   0%|          | 0/300 [00:00<?, ? examples/s]

  [train] 37/84 — 11,100/25,000 (44%)

Saving the dataset (0/1 shards):   0%|          | 0/300 [00:00<?, ? examples/s]

  [train] 38/84 — 11,400/25,000 (46%)

Saving the dataset (0/1 shards):   0%|          | 0/300 [00:00<?, ? examples/s]

  [train] 39/84 — 11,700/25,000 (47%)

Saving the dataset (0/1 shards):   0%|          | 0/300 [00:00<?, ? examples/s]

  [train] 40/84 — 12,000/25,000 (48%)

Saving the dataset (0/1 shards):   0%|          | 0/300 [00:00<?, ? examples/s]

  [train] 41/84 — 12,300/25,000 (49%)

Saving the dataset (0/1 shards):   0%|          | 0/300 [00:00<?, ? examples/s]

  [train] 42/84 — 12,600/25,000 (50%)

Saving the dataset (0/1 shards):   0%|          | 0/300 [00:00<?, ? examples/s]

  [train] 43/84 — 12,900/25,000 (52%)

Saving the dataset (0/1 shards):   0%|          | 0/300 [00:00<?, ? examples/s]

  [train] 44/84 — 13,200/25,000 (53%)

Saving the dataset (0/1 shards):   0%|          | 0/300 [00:00<?, ? examples/s]

  [train] 45/84 — 13,500/25,000 (54%)

Saving the dataset (0/1 shards):   0%|          | 0/300 [00:00<?, ? examples/s]

  [train] 46/84 — 13,800/25,000 (55%)

Saving the dataset (0/1 shards):   0%|          | 0/300 [00:00<?, ? examples/s]

  [train] 47/84 — 14,100/25,000 (56%)

Saving the dataset (0/1 shards):   0%|          | 0/300 [00:00<?, ? examples/s]

  [train] 48/84 — 14,400/25,000 (58%)

Saving the dataset (0/1 shards):   0%|          | 0/300 [00:00<?, ? examples/s]

  [train] 49/84 — 14,700/25,000 (59%)

Saving the dataset (0/1 shards):   0%|          | 0/300 [00:00<?, ? examples/s]

  [train] 50/84 — 15,000/25,000 (60%)

Saving the dataset (0/1 shards):   0%|          | 0/300 [00:00<?, ? examples/s]

  [train] 51/84 — 15,300/25,000 (61%)

Saving the dataset (0/1 shards):   0%|          | 0/300 [00:00<?, ? examples/s]

  [train] 52/84 — 15,600/25,000 (62%)

Saving the dataset (0/1 shards):   0%|          | 0/300 [00:00<?, ? examples/s]

  [train] 53/84 — 15,900/25,000 (64%)

Saving the dataset (0/1 shards):   0%|          | 0/300 [00:00<?, ? examples/s]

  [train] 54/84 — 16,200/25,000 (65%)

Saving the dataset (0/1 shards):   0%|          | 0/300 [00:00<?, ? examples/s]

  [train] 55/84 — 16,500/25,000 (66%)

Saving the dataset (0/1 shards):   0%|          | 0/300 [00:00<?, ? examples/s]

  [train] 56/84 — 16,800/25,000 (67%)

Saving the dataset (0/1 shards):   0%|          | 0/300 [00:00<?, ? examples/s]

  [train] 57/84 — 17,100/25,000 (68%)

Saving the dataset (0/1 shards):   0%|          | 0/300 [00:00<?, ? examples/s]

  [train] 58/84 — 17,400/25,000 (70%)

Saving the dataset (0/1 shards):   0%|          | 0/300 [00:00<?, ? examples/s]

  [train] 59/84 — 17,700/25,000 (71%)

Saving the dataset (0/1 shards):   0%|          | 0/300 [00:00<?, ? examples/s]

  [train] 60/84 — 18,000/25,000 (72%)

Saving the dataset (0/1 shards):   0%|          | 0/300 [00:00<?, ? examples/s]

  [train] 61/84 — 18,300/25,000 (73%)

Saving the dataset (0/1 shards):   0%|          | 0/300 [00:00<?, ? examples/s]

  [train] 62/84 — 18,600/25,000 (74%)

Saving the dataset (0/1 shards):   0%|          | 0/300 [00:00<?, ? examples/s]

  [train] 63/84 — 18,900/25,000 (76%)

Saving the dataset (0/1 shards):   0%|          | 0/300 [00:00<?, ? examples/s]

  [train] 64/84 — 19,200/25,000 (77%)

Saving the dataset (0/1 shards):   0%|          | 0/300 [00:00<?, ? examples/s]

  [train] 65/84 — 19,500/25,000 (78%)

Saving the dataset (0/1 shards):   0%|          | 0/300 [00:00<?, ? examples/s]

  [train] 66/84 — 19,800/25,000 (79%)

Saving the dataset (0/1 shards):   0%|          | 0/300 [00:00<?, ? examples/s]

  [train] 67/84 — 20,100/25,000 (80%)

Saving the dataset (0/1 shards):   0%|          | 0/300 [00:00<?, ? examples/s]

  [train] 68/84 — 20,400/25,000 (82%)

Saving the dataset (0/1 shards):   0%|          | 0/300 [00:00<?, ? examples/s]

  [train] 69/84 — 20,700/25,000 (83%)

Saving the dataset (0/1 shards):   0%|          | 0/300 [00:00<?, ? examples/s]

  [train] 70/84 — 21,000/25,000 (84%)

Saving the dataset (0/1 shards):   0%|          | 0/300 [00:00<?, ? examples/s]

  [train] 71/84 — 21,300/25,000 (85%)

Saving the dataset (0/1 shards):   0%|          | 0/300 [00:00<?, ? examples/s]

  [train] 72/84 — 21,600/25,000 (86%)

Saving the dataset (0/1 shards):   0%|          | 0/300 [00:00<?, ? examples/s]

  [train] 73/84 — 21,900/25,000 (88%)

Saving the dataset (0/1 shards):   0%|          | 0/300 [00:00<?, ? examples/s]

  [train] 74/84 — 22,200/25,000 (89%)

Saving the dataset (0/1 shards):   0%|          | 0/300 [00:00<?, ? examples/s]

  [train] 75/84 — 22,500/25,000 (90%)

Saving the dataset (0/1 shards):   0%|          | 0/300 [00:00<?, ? examples/s]

  [train] 76/84 — 22,800/25,000 (91%)

Saving the dataset (0/1 shards):   0%|          | 0/300 [00:00<?, ? examples/s]

  [train] 77/84 — 23,100/25,000 (92%)

Saving the dataset (0/1 shards):   0%|          | 0/300 [00:00<?, ? examples/s]

  [train] 78/84 — 23,400/25,000 (94%)

Saving the dataset (0/1 shards):   0%|          | 0/300 [00:00<?, ? examples/s]

  [train] 79/84 — 23,700/25,000 (95%)

Saving the dataset (0/1 shards):   0%|          | 0/300 [00:00<?, ? examples/s]

  [train] 80/84 — 24,000/25,000 (96%)

Saving the dataset (0/1 shards):   0%|          | 0/300 [00:00<?, ? examples/s]

  [train] 81/84 — 24,300/25,000 (97%)

Saving the dataset (0/1 shards):   0%|          | 0/300 [00:00<?, ? examples/s]

  [train] 82/84 — 24,600/25,000 (98%)

Saving the dataset (0/1 shards):   0%|          | 0/300 [00:00<?, ? examples/s]

  [train] 83/84 — 24,900/25,000 (100%)

Saving the dataset (0/1 shards):   0%|          | 0/100 [00:00<?, ? examples/s]

  [train] 84/84 — 25,000/25,000 (100%)
  [train] Concatenating 84 chunks...
  [train] ✅ 25,000 samples ready

=== Extracting TEST features ===

Saving the dataset (0/1 shards):   0%|          | 0/300 [00:00<?, ? examples/s]

  [test] 1/1 — 300/300 (100%)
  [test] Concatenating 1 chunks...
  [test] ✅ 300 samples ready

✅ Feature extraction complete
  Train : 25,000
  Test  : 300
  Shape : (80, 3000)

In [11]:
# WHY a custom collator:
# input_features are fixed-size (80×3000) — just stack them.
# labels are variable-length — pad to the longest in the batch.
# Padding positions are replaced with -100 so CrossEntropyLoss ignores them.

@dataclass
class DataCollatorWhisper:
    processor: Any
    decoder_start_token_id: int

    def __call__(self, features: List[Dict[str, Any]]) -> Dict[str, torch.Tensor]:
        # Stack spectrograms — already same shape, no padding needed
        input_features = [
            {'input_features': f['input_features']} for f in features
        ]
        batch = self.processor.feature_extractor.pad(
            input_features, return_tensors='pt'
        )

        # Pad label sequences to uniform length within this batch
        label_features = [{'input_ids': f['labels']} for f in features]
        labels_batch   = self.processor.tokenizer.pad(
            label_features, return_tensors='pt'
        )

        # Replace pad token with -100 → ignored by loss
        labels = labels_batch['input_ids'].masked_fill(
            labels_batch.attention_mask.ne(1), -100
        )

        # Strip decoder start token if present (model adds it itself)
        if (labels[:, 0] == self.decoder_start_token_id).all().cpu().item():
            labels = labels[:, 1:]

        batch['labels'] = labels
        return batch


data_collator = DataCollatorWhisper(
    processor=processor,
    decoder_start_token_id=model.config.decoder_start_token_id,
)
print('Data collator ready')

Data collator ready

In [12]:
# WHY WER over loss for model selection:
# Validation loss measures next-token prediction probability,
# but WER measures actual transcription quality — what we care about.
# A model with lower loss can have HIGHER WER if it memorizes token patterns
# but fails to generalize to the actual word sequence.

wer_metric = evaluate.load('wer')

def compute_metrics(pred):
    pred_ids  = pred.predictions
    label_ids = pred.label_ids

    # Restore pad tokens so the tokenizer can decode properly
    label_ids[label_ids == -100] = processor.tokenizer.pad_token_id

    pred_str  = processor.batch_decode(pred_ids,  skip_special_tokens=True)
    label_str = processor.batch_decode(label_ids, skip_special_tokens=True)

    # Normalize BOTH sides — same function used on ground truth at training time
    # This prevents WER inflation from diacritic differences
    pred_str  = [normalize_arabic(s) for s in pred_str]
    label_str = [normalize_arabic(s) for s in label_str]

    # Filter empty predictions (can happen on very short/silent clips)
    pairs = [(p, l) for p, l in zip(pred_str, label_str) if l.strip()]
    if not pairs:
        return {'wer': 100.0}

    preds, labels = zip(*pairs)
    wer = 100 * wer_metric.compute(predictions=list(preds), references=list(labels))
    return {'wer': round(wer, 2)}


print('WER metric ready')

Downloading builder script: 0.00B [00:00, ?B/s]

WER metric ready

In [13]:
# Detect if we can use bf16 (Ampere+ GPUs) vs fp16 (T4/V100)
# use_bf16 = torch.cuda.is_available() and torch.cuda.is_bf16_supported()
# use_fp16 = torch.cuda.is_available() and not use_bf16
# print(f'Mixed precision: {"bf16" if use_bf16 else "fp16" if use_fp16 else "none (CPU)"}')
use_bf16 = False
use_fp16 = True
print(f'Mixed precision forced to: fp16 for T4 optimization')
# Check for existing checkpoint to resume from
resume_checkpoint = None
if os.path.isdir(CFG['output_dir']):
    checkpoints = [
        d for d in os.listdir(CFG['output_dir'])
        if d.startswith('checkpoint-')
    ]
    if checkpoints:
        latest = sorted(checkpoints, key=lambda x: int(x.split('-')[1]))[-1]
        resume_checkpoint = os.path.join(CFG['output_dir'], latest)
        print(f'Resuming from checkpoint: {resume_checkpoint}')
    else:
        print('No checkpoint found — training from scratch')


# Dropout zeroed: short fine-tuning runs on a clean scripted-speech corpus
# don't need extra regularization, and dropout slows convergence.
model.config.activation_dropout = 0.05
model.config.attention_dropout = 0.05
model.config.apply_spec_augment = True
model.config.mask_time_prob = 0.05
model.config.mask_feature_prob = 0.05
training_args = Seq2SeqTrainingArguments(
    output_dir=CFG['output_dir'],

    # ── Batch ──────────────────────────────────────────────────────────
    per_device_train_batch_size=CFG['batch_size'],
    gradient_accumulation_steps=CFG['grad_accumulation'],
    # Bigger eval batch → faster generation passes (eval is the bottleneck once
    # gradient checkpointing is off).
    per_device_eval_batch_size=CFG['batch_size'],

    # ── Schedule ───────────────────────────────────────────────────────
    learning_rate=CFG['learning_rate'],
    warmup_steps=CFG['warmup_steps'],
    lr_scheduler_type='cosine',   # linear decay helps avoid overfitting on small sets
    max_steps=CFG['max_steps'],
    weight_decay=CFG['weight_decay'],

    # ── Eval & saving ──────────────────────────────────────────────────
    eval_strategy='steps',
    eval_steps=CFG['eval_steps'],
    save_strategy='steps',
    save_steps=CFG['save_steps'],
    save_total_limit=2,           # keep only last 2 checkpoints → saves disk
    logging_steps=CFG['logging_steps'],

    # ── Best model selection ───────────────────────────────────────────
    load_best_model_at_end=True,
    metric_for_best_model='wer',
    greater_is_better=False,      # lower WER is better

    # ── Generation ─────────────────────────────────────────────────────
    predict_with_generate=True,
    # CV Arabic transcripts are short (~10-15 tokens). 80 is plenty and roughly
    # halves eval generation time vs. 128.
    generation_max_length=80,

    # ── Memory / speed ─────────────────────────────────────────────────
    fp16=use_fp16,
    bf16=use_bf16,
    # Gradient checkpointing OFF: whisper-small fits comfortably on T4 (16GB)
    # at batch 16 fp16 without it. Turning it off is ~25-30% faster wall time.
    gradient_checkpointing=False,
    optim='adamw_torch',

    # ── Data loading ───────────────────────────────────────────────────
    # num_workers=0: dataset is in RAM, workers add overhead not speed
    dataloader_num_workers=CFG['num_workers'],
    dataloader_pin_memory=True,
    remove_unused_columns=False,

    # ── Misc ───────────────────────────────────────────────────────────
    report_to=['tensorboard'],
    push_to_hub=False,
)

trainer = Seq2SeqTrainer(
    args=training_args,
    model=model,
    train_dataset=dataset['train'],
    eval_dataset=dataset['test'],
    data_collator=data_collator,
    compute_metrics=compute_metrics,
    processing_class=processor.feature_extractor,
    callbacks=[
        # Stop early if WER doesn't improve — prevents overfitting on small sets
        EarlyStoppingCallback(
            early_stopping_patience=CFG['early_stopping_patience']
        )
    ],
)

eff_batch = CFG['batch_size'] * CFG['grad_accumulation']
print(f'Trainer ready')
print(f'  Effective batch size : {eff_batch}')
print(f'  Max steps            : {CFG["max_steps"]}')
print(f'  Eval every           : {CFG["eval_steps"]} steps')
print(f'  Resume checkpoint    : {resume_checkpoint or "None"}')

Mixed precision forced to: fp16 for T4 optimization
No checkpoint found — training from scratch

2026-04-29 09:15:56.523108: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:467] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
E0000 00:00:1777454156.961635      23 cuda_dnn.cc:8579] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
E0000 00:00:1777454157.090395      23 cuda_blas.cc:1407] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
W0000 00:00:1777454158.195642      23 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1777454158.195675      23 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1777454158.195680      23 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1777454158.195686      23 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.

Trainer ready
  Effective batch size : 32
  Max steps            : 2000
  Eval every           : 500 steps
  Resume checkpoint    : None

In [14]:
# WHY evaluate before training:
# This gives you the baseline WER of the pretrained Whisper-small on Arabic.
# The difference between baseline and post-training WER is your key CV metric.
print('Evaluating baseline WER (pretrained, no fine-tuning)...')
print('This takes ~3–5 minutes on T4...')

# 1. Find and temporarily remove the notebook callback (no import needed)
notebook_callback = None
for callback in trainer.callback_handler.callbacks:
    if callback.__class__.__name__ == 'NotebookProgressCallback':
        notebook_callback = callback
        break

if notebook_callback is not None:
    trainer.remove_callback(notebook_callback)

# 2. Run the evaluation
baseline = trainer.evaluate()
BASELINE_WER = baseline['eval_wer']

# 3. Add the exact callback instance back for training
if notebook_callback is not None:
    trainer.add_callback(notebook_callback)

print(f'\n{"="*45}')
print(f'  BASELINE WER : {BASELINE_WER:.2f}%')
print(f'{"="*45}')
print('Record this number — it goes on your CV.')

Evaluating baseline WER (pretrained, no fine-tuning)...
This takes ~3–5 minutes on T4...

[transformers] The attention mask is not set and cannot be inferred from input because pad token is same as eos token. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
[transformers] A custom logits processor of type <class 'transformers.generation.logits_process.SuppressTokensLogitsProcessor'> has been passed to `.generate()`, but it was also created in `.generate()`, given its parameterization. The custom <class 'transformers.generation.logits_process.SuppressTokensLogitsProcessor'> will take precedence. Please check the docstring of <class 'transformers.generation.logits_process.SuppressTokensLogitsProcessor'> to see related `.generate()` flags.
[transformers] A custom logits processor of type <class 'transformers.generation.logits_process.SuppressTokensAtBeginLogitsProcessor'> has been passed to `.generate()`, but it was also created in `.generate()`, given its parameterization. The custom <class 'transformers.generation.logits_process.SuppressTokensAtBeginLogitsProcessor'> will take precedence. Please check the docstring of <class 'transformers.generation.logits_process.SuppressTokensAtBeginLogitsProcessor'> to see related `.generate()` flags.
/usr/local/lib/python3.12/dist-packages/torch/autograd/function.py:583: UserWarning: Was asked to gather along dimension 0, but all input tensors were scalars; will instead unsqueeze and return a vector.
  return super().apply(*args, **kwargs)  # type: ignore[misc]
[transformers] Ignoring clean_up_tokenization_spaces=True for BPE tokenizer WhisperTokenizer. The clean_up_tokenization post-processing step is designed for WordPiece tokenizers and is destructive for BPE (it strips spaces before punctuation). Set clean_up_tokenization_spaces=False to suppress this warning, or set clean_up_tokenization_spaces_for_bpe_even_though_it_will_corrupt_output=True to force cleanup anyway.

=============================================
  BASELINE WER : 42.69%
=============================================
Record this number — it goes on your CV.

In [15]:
# WHY resume_from_checkpoint:
# Kaggle sessions can time out. If the notebook restarts and checkpoints exist,
# training picks up from the last saved step rather than starting over.
# The `resume_checkpoint` variable was set in Cell 8 to the latest checkpoint.

print('Starting fine-tuning...')
eff_batch = CFG['batch_size'] * CFG['grad_accumulation']
samples_per_step = eff_batch
total_samples    = CFG['max_steps'] * samples_per_step
print(f'  Will process ~{total_samples:,} samples across {CFG["max_steps"]} steps')
print(f'  (dataset has {len(dataset["train"]):,} samples = '
      f'{total_samples / len(dataset["train"]):.1f} passes through data)')

train_result = trainer.train(resume_from_checkpoint=resume_checkpoint)

print('\nFine-tuning complete!')
print(f'  Train runtime : {train_result.metrics["train_runtime"]:.0f}s '
      f'({train_result.metrics["train_runtime"]/3600:.1f}h)')
print(f'  Train loss    : {train_result.metrics["train_loss"]:.4f}')

Starting fine-tuning...
  Will process ~64,000 samples across 2000 steps
  (dataset has 25,000 samples = 2.6 passes through data)

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

/usr/local/lib/python3.12/dist-packages/torch/autograd/function.py:583: UserWarning: Was asked to gather along dimension 0, but all input tensors were scalars; will instead unsqueeze and return a vector.
  return super().apply(*args, **kwargs)  # type: ignore[misc]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

/usr/local/lib/python3.12/dist-packages/torch/autograd/function.py:583: UserWarning: Was asked to gather along dimension 0, but all input tensors were scalars; will instead unsqueeze and return a vector.
  return super().apply(*args, **kwargs)  # type: ignore[misc]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

/usr/local/lib/python3.12/dist-packages/torch/autograd/function.py:583: UserWarning: Was asked to gather along dimension 0, but all input tensors were scalars; will instead unsqueeze and return a vector.
  return super().apply(*args, **kwargs)  # type: ignore[misc]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

[transformers] There were missing keys in the checkpoint model loaded: ['proj_out.weight'].

Fine-tuning complete!
  Train runtime : 32096s (8.9h)
  Train loss    : 2.0911

In [16]:
print('Evaluating fine-tuned model...')
final = trainer.evaluate()
FINAL_WER = final['eval_wer']

print(f'\n{"="*45}')
print(f'  BASELINE WER   : {BASELINE_WER:.2f}%')
print(f'  FINE-TUNED WER : {FINAL_WER:.2f}%')
abs_improvement = BASELINE_WER - FINAL_WER
rel_improvement = abs_improvement / BASELINE_WER * 100
print(f'  IMPROVEMENT    : {abs_improvement:.2f}pp absolute  '
      f'({rel_improvement:.1f}% relative)')
print(f'{"="*45}')

# Save results to JSON for your README
results = {
    'model':          CFG['model_name'],
    'n_train':        CFG['n_train'],
    'n_test':         CFG['n_test'],
    'max_steps':      CFG['max_steps'],
    'baseline_wer':   round(BASELINE_WER, 2),
    'finetuned_wer':  round(FINAL_WER, 2),
    'abs_improvement': round(abs_improvement, 2),
    'rel_improvement': round(rel_improvement, 1),
}
with open(os.path.join(CFG['output_dir'], 'results.json'), 'w') as f:
    json.dump(results, f, indent=2)
print(f'\nResults saved to {CFG["output_dir"]}/results.json')

Evaluating fine-tuned model...

/usr/local/lib/python3.12/dist-packages/torch/autograd/function.py:583: UserWarning: Was asked to gather along dimension 0, but all input tensors were scalars; will instead unsqueeze and return a vector.
  return super().apply(*args, **kwargs)  # type: ignore[misc]

=============================================
  BASELINE WER   : 42.69%
  FINE-TUNED WER : 21.31%
  IMPROVEMENT    : 21.38pp absolute  (50.1% relative)
=============================================

Results saved to /kaggle/working/whisper-arabic/results.json

In [17]:
SAVE_PATH = os.path.join(CFG['output_dir'], 'final-model')

trainer.save_model(SAVE_PATH)
processor.save_pretrained(SAVE_PATH)

print(f'Model saved to: {SAVE_PATH}')
print('\nFiles:')
for f in sorted(os.listdir(SAVE_PATH)):
    size_mb = os.path.getsize(os.path.join(SAVE_PATH, f)) / 1e6
    print(f'  {f:<40s} {size_mb:>8.1f} MB')

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Model saved to: /kaggle/working/whisper-arabic/final-model

Files:
  config.json                                   0.0 MB
  generation_config.json                        0.0 MB
  model.safetensors                           967.0 MB
  preprocessor_config.json                      0.0 MB
  processor_config.json                         0.0 MB
  tokenizer.json                                3.9 MB
  tokenizer_config.json                         0.0 MB
  training_args.bin                             0.0 MB

In [18]:
# Show 5 random test samples with ground truth vs prediction

model.eval()
device = 'cuda' if torch.cuda.is_available() else 'cpu'
model.to(device)

print('=== Sample Transcriptions ===')
print(f'{"─"*70}')

# Pick 5 random test samples
indices = np.random.default_rng(0).integers(0, len(df_test_raw), size=5)

for idx in indices:
    row = df_test_raw.iloc[idx]
    try:
        audio, _ = librosa.load(row['audio_path'], sr=16000, mono=True)
        duration  = len(audio) / 16000

        inputs = processor(
            audio,
            sampling_rate=16000,
            return_tensors='pt',
        ).input_features.to(device)

        with torch.no_grad():
            predicted_ids = model.generate(
                inputs,
                language='arabic',
                task='transcribe',
                max_new_tokens=128,
            )

        prediction   = processor.batch_decode(predicted_ids, skip_special_tokens=True)[0]
        ground_truth = row['sentence']

        pred_norm = normalize_arabic(prediction)
        ref_norm  = normalize_arabic(ground_truth)

        # Sample-level WER
        sample_wer = wer_metric.compute(
            predictions=[pred_norm],
            references=[ref_norm],
        ) * 100 if ref_norm else 0.0

        print(f'Duration : {duration:.1f}s')
        print(f'Reference: {ground_truth}')
        print(f'Predicted: {prediction}')
        print(f'WER      : {sample_wer:.1f}%')
        print(f'{"─"*70}')

    except Exception as e:
        print(f'[sample {idx}] Error: {e}')
        print(f'{"─"*70}')

=== Sample Transcriptions ===
──────────────────────────────────────────────────────────────────────

[transformers] Both `max_new_tokens` (=128) and `max_length`(=448) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
[transformers] Both `max_new_tokens` (=128) and `max_length`(=448) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

Duration : 4.3s
Reference: هاملت مسرحيه لشكسبير
Predicted: هاملت مسرحيه لشيكس بير
WER      : 66.7%
──────────────────────────────────────────────────────────────────────

[transformers] Both `max_new_tokens` (=128) and `max_length`(=448) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

Duration : 5.3s
Reference: لا تعتقد بانك ستتخلص مني بهذه السهوله
Predicted: لا تعتقد بانك ستتخلص مني بهذه الصهوله
WER      : 14.3%
──────────────────────────────────────────────────────────────────────

[transformers] Both `max_new_tokens` (=128) and `max_length`(=448) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

Duration : 3.5s
Reference: نحن نعيش علي كوكب الارض
Predicted: نحن نعيش علي كوكب الارض
WER      : 0.0%
──────────────────────────────────────────────────────────────────────

[transformers] Both `max_new_tokens` (=128) and `max_length`(=448) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

Duration : 3.6s
Reference: كانت ليلي تخطط لسرقه مصرف
Predicted: كانت ليلي تخطط لسرقه في مصره
WER      : 40.0%
──────────────────────────────────────────────────────────────────────
Duration : 4.0s
Reference: لم يفعل فاضل شيئا
Predicted: لم يفعل فاضل شيئا
WER      : 0.0%
──────────────────────────────────────────────────────────────────────

In [19]:
print('## Results\n')
print('| Metric               | Value                      |')
print('|----------------------|----------------------------|')
print(f'| Model                | {CFG["model_name"]}  |')
print(f'| Training samples     | {CFG["n_train"]:,}                     |')
print(f'| Test samples         | {CFG["n_test"]:,}                      |')
print(f'| Training steps       | {CFG["max_steps"]:,}                      |')
print(f'| Baseline WER         | {BASELINE_WER:.2f}%                    |')
print(f'| Fine-tuned WER       | {FINAL_WER:.2f}%                    |')
print(f'| Absolute improvement | {BASELINE_WER - FINAL_WER:.2f}pp                   |')
print(f'| Relative improvement | {(BASELINE_WER-FINAL_WER)/BASELINE_WER*100:.1f}%                    |')
print(f'| Dataset              | Common Voice 25.0 Arabic   |')

## Results

| Metric               | Value                      |
|----------------------|----------------------------|
| Model                | openai/whisper-small  |
| Training samples     | 25,000                     |
| Test samples         | 300                      |
| Training steps       | 2,000                      |
| Baseline WER         | 42.69%                    |
| Fine-tuned WER       | 21.31%                    |
| Absolute improvement | 21.38pp                   |
| Relative improvement | 50.1%                    |
| Dataset              | Common Voice 25.0 Arabic   |